server:
  port: 9009
  servlet-path: /
netty:
  socketio:
    host: 127.0.0.1
    port: 10086

spring:
  datasource:
    default:
      url: jdbc:mysql://47.93.224.244:3306/mahjong?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: Wx@900921
      driver-class-name: com.mysql.jdbc.Driver
logging:
  level: debug


#  main:
#    banner-mode: "off"
