server:
  port: 9009
  servlet-path: /
netty:
  socketio:
    host: 192.168.3.2
    port: 10086

spring:
  datasource:
    default:
      url: jdbc:mysql://127.0.0.1:3306/mahjong?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
logging:
  level: debug


#  main:
#    banner-mode: "off"
